package ss7_abstract_class_and_interface.thuc_hanh.class_animal_interface_edible.fruit;

import ss7_abstract_class_and_interface.thuc_hanh.class_animal_interface_edible.edible.IEdible;

public abstract class Fruit implements IEdible{ }